services:
  node:
    image: node:latest
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm start -- --host=0.0.0.0
    ports:
      - 8000:8000
    expose:
      - 8000
